Tum : derleme calistirma

derleme:
	g++ -I ./include -o ./lib/Dugum.o -c ./src/Dugum.cpp
	g++ -I ./include -o ./lib/BagilListe.o -c ./src/BagilListe.cpp
	g++ -I ./include ./src/Dugum.cpp ./src/BagilListe.cpp ./src/Test.cpp -o ./bin/Test
calistirma:
	./bin/Test